Fix fix my profile css
somegram-frontend/inctagram-client-front pull request #25
Opened 2024-11-08 11:52 UTC by MacheteBy

2024-11-08 18:11 UTC, ViktorChizh requested changes

2024-11-08 18:11 UTC, ViktorChizh commented on src/shared/const/validationSchemas.ts
>        }
вроде в прямых кавычках так и напечатает как текст и теги. ты точно проверял результат?

2024-11-08 18:11 UTC, ViktorChizh commented on src/shared/const/validationSchemas.ts
>        },
если придираться, то тут не учтены високосные года. имхо, надо найти библиотеку, которая корректно подсчитывает года.

2024-11-08 18:11 UTC, ViktorChizh commented on src/pages/user/[id]/privacyPolicy/index.tsx
> +const PrivacyPolicy = () => {
такая компонента есть в регистрации. там тоже нужна была прайваси полиси. используй ту, не дублируй

2024-11-08 18:11 UTC, ViktorChizh commented on src/components/datePicker/index.tsx
> +          <div className={clsx(s.hasError)} dangerouslySetInnerHTML={{ __html: errorMessage }} />
впервые вижу такое применение дива. ты точно уверен, что это печатается?

2024-11-08 18:11 UTC, ViktorChizh commented on src/pages/user/[id]/privacyPolicy/privacyPolicy.module.scss
> +.privacy {
тоже самое - стили есть в компоненте в регистрации

2024-11-09 13:47 UTC, AnatolyNikol commented on src/components/datePicker/index.tsx
> +          <div className={clsx(s.hasError)} dangerouslySetInnerHTML={{ __html: errorMessage }} />
Согласен, при первом поиске сразу выдаётся информация "dangerouslySetInnerHTML - это замена React для использования innerHTML в DOM браузера. Вообще, задавать HTML из кода рискованно, так как можно случайно подвергнуть пользователей атаке межсайтового скриптинга (XSS). Итак, вы можете задавать HTML прямо из React, но вам придется набрать dangerouslySetInnerHTML и передать объект с ключом __html, чтобы напомнить себе, что это опасно."
Поскольку zod не позволяет вставлять ссылки, не нужно его пытаться обмануть, просто оставь сообщение.

2024-11-09 14:33 UTC, AnatolyNikol commented on src/shared/const/validationSchemas.ts
>        }
Здесь только текст оставь. 'A user under 13 cannot create a profile.'

2024-11-09 14:38 UTC, AnatolyNikol approved these changes

2024-11-11 18:50 UTC, MacheteBy commented on src/shared/const/validationSchemas.ts
>        }
да, оно работает. переделаю по другому.

2024-11-11 18:50 UTC, MacheteBy commented on src/shared/const/validationSchemas.ts
>        },
давай не будем придираться)

2024-11-12 03:56 UTC, ViktorChizh approved these changes

2024-11-12 07:23 UTC, merged